[config]
schemaVersion = "0.0.1"

[package]
namespace = "Multiplayer"
name = "Multiplayer"
versionNumber = "0.1.6"
description = "Multiplayer"
websiteUrl = "https://github.com/asd9176506911298/NineSols-Multiplayer"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "0.4.1"
"ninesolsmodding-BepinExConfigurationManager" = "18.3.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
